version: "3.8"
services:
  reg-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-deep-down-dark-secret
      MYSQL_DATABASE: registration
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/migration.sql:/docker-entrypoint-initdb.d/init.sql
  reg-api:
    build: .
    environment:
      MYSQL_HOST: reg-db
    ports:
      - 8080:8080
    depends_on:
      - reg-db